### ISSUE TITLE
[PROPOSAL] Improve IndexArray

### ISSUE THREAD

**Issue by solan-solan** [axis-project/axis#711]
Some noticement about new IndexArray:

Why 'at' function is template?
![image](https://user-images.githubusercontent.com/73186496/177405896-577d0ef7-d1c5-4faf-902c-df41d88d4669.png)
 If you know _stride, you know size of keeping elements.
As it is now, I need to instantiate template function explicitly, otherwise error:
![image](https://user-images.githubusercontent.com/73186496/177406611-251901e2-95ce-4b60-9d82-f746bb0f767f.png)

Returned type could be IndexFormat::U_INT as maximum size index format

Besides, is it possible to implement the following api for IndexArray ?

IndexArray::operator[]
IndexArray::begin()
IndexArray::end()
IndexArray::erase(iterator_from, iterator_to) - (There is no _erase_ function for underlying type _yasio::byte_buffer_ at all)

**Comment by solan-solan** [comment]
If it is not simple to implement the function as non template, then the solution could be to define default template parameter, like this:
![image](https://user-images.githubusercontent.com/73186496/177436814-ee67695b-9cb0-4eb1-8330-97e5b1337b4e.png)

**Comment by halx99** [comment]
> If it is not simple to implement the function as non template, then the solution could be to define default template parameter, like this: ![image](https://user-images.githubusercontent.com/73186496/177436814-ee67695b-9cb0-4eb1-8330-97e5b1337b4e.png)

looks good.

**Comment by halx99** [comment]
Implement `at` as template is for readwrite operation, certainly, we can add two fuction like:
```cpp
void seti(size_t idx, uint32_t val);
uint32_t geti(size_t idx);
```

**Comment by halx99** [comment]
Hide `begin`, `end` stubs, because we don't want user use for loop external, just use `IndexArray::for_each` instead.

**Comment by halx99** [comment]
> Hide `begin`, `end` stubs, because we don't want user use for loop external, just use `IndexArray::for_each` instead.

Certainly, we can make the `begin`, `end` stubs return `void*` to for the same purpose.

**Comment by halx99** [comment]
> > Certainly, we can make the begin, end stubs return void* to for the same purpose.
> 
> It is a normal practice to provide _begin/end_ api since there is opportunity to random access with _at_ according to stl.
> 
> But, you could implement it like _at_ template and return pointer to __Ty_ rather then _void*_ to keep opportunity for +/- operations, since, as I properly understand, iterator in terms of yasio::byte_buffer is pointer to keeping element and default_allocator allocates linear array

ok, will do
