### ISSUE TITLE
[PROBOSAL] Replace all cocos2dx 'HelloWorld.png' with the 'ADXE<xxx>.png' (at the moment as draft)

### ISSUE THREAD

**Issue by aismann** [axis-project/axis#722]
I think the name: 'ADXE' is fixed now.
Now we have to change the 'Splash Screen and the Icon':
Probosal:
Use this for white backgrounds (ADXE_white.png):
![image](https://user-images.githubusercontent.com/45469625/174136545-92e177e9-2a3d-4edd-9555-bbc43b2b63d2.png)
And use this for black backgrounds  (ADXE_black.png): 
![image](https://user-images.githubusercontent.com/45469625/174136724-acda1f27-0810-45e9-8645-8d6df92ae513.png)
Colored versions  (ADXE_color.png):
![image](https://user-images.githubusercontent.com/8652787/177692276-76c6c5a9-9b70-41cf-9697-52ad7f917aab.png)
What are you mean? I think its better we having this new three ADXE images as drafts instead the Cocos2DX.
The developer can choose which one he want to use.
Missing: An ADXE icon.
Here only a bad example:
![image](https://user-images.githubusercontent.com/8652787/177694865-71a5482f-7dc3-4467-8b8a-2d11618be4bb.png)

The easiest way is to use the colored one only and rename it to 'HelloWorld.png'. 
=> no sources have to be adapt (only all 'HelloWorld.png' have to be replaced)

**Comment by DelinWorks** [comment]
@aismann I like the original one, the colored one looks like a random kids' toy company not to be offensive or anything.

**Comment by halx99** [comment]
Maybe the logo needs redesign, for adxe means: ` ahead x engine`

**Comment by DelinWorks** [comment]
Game engine names should not have a multi sentence name like amazing game engine or ahead game engine, the name becomes weird this way! do you see godot name their engine with a multi word sentence? no same goes for unreal and unity, it should be a simple generic one word, that's how you pick a good name. hope that helps 🙂

Ofcourse what i said goes for naming anything not just game engines, in the end, it's up to you guys to decide.

**Comment by halx99** [comment]
It's hard to decide a good name (looks and hear good) for me.

**Comment by halx99** [comment]
> It's hard to decide a good name (looks and hear good) for me, or call `axes`

![image](https://user-images.githubusercontent.com/6977319/177714345-55788cc5-25e1-4dfe-bf96-d4cae7530de7.png)

**Comment by aismann** [comment]
Needs adxe realy a declaration?

**Comment by DelinWorks** [comment]
you axis? that name is great!

**Comment by DelinWorks** [comment]
> Needs adxe realy a declaration?

Unfortunately, yes for the game engine to popup in search results

**Comment by halx99** [comment]
> you axis? that name is great!

Yeah, multi axis could be `axes` or `axis`

**Comment by aismann** [comment]
> > you axis? that name is great!
> 
> Yeah, multi axis could be `axes` or `axis`

No prob for me. ;)

**Comment by DelinWorks** [comment]
> > you axis? that name is great!
> 
> Yeah, multi axis could be `axes` or `axis`

nah leave the axe 🪓 thingy it sounds weird, we can actually stick to `axis` like in xyz it sounds cool!

**Comment by aismann** [comment]
> @aismann I like the original one, the colored one looks like a random kids' toy company not to be offensive or anything.

no prob, only the cloud should be more blue ;)

**Comment by aismann** [comment]
> > It's hard to decide a good name (looks and hear good) for me, or call `axes`
> 
> ![image](https://user-images.githubusercontent.com/6977319/177714345-55788cc5-25e1-4dfe-bf96-d4cae7530de7.png)

I like the 'abtract image.
Of course it have to improve too ;)

**Comment by DelinWorks** [comment]
also the name `axis` hints to the game engine's 3D capabilities! i like it.

**Comment by halx99** [comment]
> > > It's hard to decide a good name (looks and hear good) for me, or call `axes`
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/6977319/177714345-55788cc5-25e1-4dfe-bf96-d4cae7530de7.png)
> 
> I like the 'abtract image. Of course it have to improve too ;)

Aha, I just use mspaint create draft image for explain

**Comment by halx99** [comment]
> also the name `axis` hints to the game engine's 3D capabilities! i like it.

so, `axis` or `axes`, what do you prefer?

**Comment by DelinWorks** [comment]
> > also the name `axis` hints to the game engine's 3D capabilities! i like it.
> 
> so, `axis` or `axes`, what do you prefer?

axis as in xyz so `axis`

**Comment by DelinWorks** [comment]
you guys can scrap the axe 🪓 idea it's irrelevant

**Comment by halx99** [comment]
OK, so the  organization or name  can be rename to `axis-project` or `axis-engine`

**Comment by DelinWorks** [comment]
Now it has meaning behind the name! nice.

**Comment by aismann** [comment]
> OK, so the organization or name can be rename to `axis-project` or `axis-engine`

I like `axis-project` more (it is more open for new ideas, not only an engine) ;)
Great step to a new way with axis ;)

**Comment by DelinWorks** [comment]
@halx99 good job with choosing the name it's dope!

**Comment by halx99** [comment]
OK, I just create it https://github.com/orgs/axis-project

**Comment by aismann** [comment]
will 'https://github.com/orgs/axis-projects' not better?
Not only one project ;)

**Comment by halx99** [comment]
I think it's ok, there are good projects: `angleproject` `llvm-project`

**Comment by halx99** [comment]
https://github.com/llvm/llvm-project

**Comment by aismann** [comment]
Like you this one?
![image](https://user-images.githubusercontent.com/8652787/177719961-c92ff243-d93d-427c-b255-87a640095125.png)

**Comment by halx99** [comment]
Because github is so powerful, we can transfer adxe to `axis-project` then rename it first. github will auto redict to new project url

**Comment by halx99** [comment]
No

**Comment by halx99** [comment]
We will not lose everythings, I compalte transfer

**Comment by DelinWorks** [comment]
I will think of a logo sometime soon

**Comment by halx99** [comment]
Now the new url is: https://github.com/axis-project/axis

**Comment by aismann** [comment]
> I will think of a logo sometime soon
Here an idee?
![image](https://user-images.githubusercontent.com/8652787/177719961-c92ff243-d93d-427c-b255-87a640095125.png)

The letter have to be in front of the blue line of course
And all Uppercase too

**Comment by halx99** [comment]
Maybe, this issue can be close as parent issue: #724

**Comment by aismann** [comment]
Yes

**Comment by DelinWorks** [comment]
> > I will think of a logo sometime soon
> 
> Here an idee? ![image](https://user-images.githubusercontent.com/8652787/177719961-c92ff243-d93d-427c-b255-87a640095125.png) The letter have to be in front of the blue line of course And all Uppercase too
> 
> And the Icon can be only the colored lines ![image](https://user-images.githubusercontent.com/8652787/177726168-274bbe2b-45e6-49ae-af19-4e9ff8bcd2c5.png)

@aismann it would look cool ngl
