### ISSUE TITLE
[PROPOSAL] Add more useful GitHub labels.

### ISSUE THREAD

**Issue by DelinWorks** [axis-project/axis#727]
The current labels are not enough to categorize an issue or a PR so the below labels should be added to mitigate that:

`breaks compatibility`
`confirmed`
`crash`
`documentation`
`feature proposal`
`high priority`
`needs testing`
`needs work`
`performance`

`platform:windows`
`platform:linux`
`platform:macos`
`platform:android`
`platform:ios`

`regression`

`topic:core`
`topic:extension`
`topic:thirdparty`
`topic:tests`
`topic:network`
`topic:physics`
`topic:input`
`topic:audio`
`topic:rendering`
`topic:shaders`
`topic:2D`
`topic:3D`
`topic:cpp`
`topic:lua`
`topic:codestyle`
`topic:porting`

**Comment by halx99** [comment]
Done
