### ISSUE TITLE
Issues with `IndexArray`

### ISSUE THREAD

**Issue by DelinWorks** [axis-project/axis#741]
The code below won't compile after #734 

![image](https://user-images.githubusercontent.com/45469625/178134968-51e4b489-887a-4a57-be93-cc69226dad36.png)

First of all, why does the function `end()` have a template? since the buffer is in bytes it doesn't have to be a templated type, Also the byte_buffer can only accept unsigned char* only and passing a template to it like in here with `position`:

![image](https://user-images.githubusercontent.com/45469625/178135023-f762b818-f5f7-459c-aaba-dcae65ff9aa8.png)

Causes compilation errors:

![image](https://user-images.githubusercontent.com/45469625/178135032-69fe1996-3828-4c43-a30d-706c9a0838ec.png)

**Comment by DelinWorks** [comment]
Still not fixed, the code below is fixed, right? it throws a `vector subscript out of range` when it comes to calculating AABB in mesh generation.

![image](https://user-images.githubusercontent.com/45469625/178148398-8a565167-94e0-4e3a-9ad8-bcc032ad148c.png)

**Comment by halx99** [comment]
Please try again after commit: https://github.com/axis-project/axis/commit/8bbcf8033030e6eb6e922644a1dd6bed890e19f7

**Comment by solan-solan** [comment]
@halx99 Take a look here please:
![image](https://user-images.githubusercontent.com/73186496/178164585-942394a2-1413-401d-baa5-de9e3ac14bef.png)

It should be the folloiwing for proper usage:
![image](https://user-images.githubusercontent.com/73186496/178165301-a4698a24-5a85-44f0-812c-7293c73a4fba.png)



![image](https://user-images.githubusercontent.com/73186496/178165286-fc007f35-f6e9-441c-b49a-2e3256906efb.png)

**Comment by DelinWorks** [comment]
> Please try again after commit: [8bbcf80](https://github.com/axis-project/axis/commit/8bbcf8033030e6eb6e922644a1dd6bed890e19f7)

Still doesn't work 
![image](https://user-images.githubusercontent.com/45469625/178166911-68c22109-de4c-4b70-b978-fcbfe9f37a02.png)

**Comment by DelinWorks** [comment]
casting the being and end iterator to `yasio::byte_buffer::iterator` works as @solan-solan suggested! it's not throwing errors now

**Comment by halx99** [comment]
OK, I will sync byte_buffer to solve this issue:
https://github.com/yasio/yasio/commit/94a10aea1df74d25c700a270e66307204f3a2537 since the byte_buffer concept shoud store everything as byte sequence
