### ISSUE TITLE
[cpp-tests] Test 27: Node Clipping UI disappear

### ISSUE THREAD

**Issue by qoozta** [axis-project/axis#742]
- axis version: dev/986540d
- devices test on: iPhone SE 2 (iOS 14.6)
- developing environments
   - Xcode version: 13.4.1
   - cmake version: 3.23.2

Steps to Reproduce:
1. Generate the cpp_test Xcode project.
2. Open and run the project on device.
3. Go to Test 27: Node Clipping, navigate to sub-test 9 and back to sub-test 8.
Sub-test 9:
![IMG_0044](https://user-images.githubusercontent.com/19526933/178186975-3a94eab3-905a-4822-b89e-201018d01db7.PNG)
Back to sub-test 8.
![IMG_0045](https://user-images.githubusercontent.com/19526933/178186988-16862854-1d12-4776-bdd2-a21ec5dae15c.PNG)

**Comment by aismann** [comment]
On window its '30: Node: Clipping'
Same behavior here

**Comment by qoozta** [comment]
CCRenderer.cpp L866 add
`_callbackCommandsPool.push_back(command);`
seems fixed the problem.

**Comment by halx99** [comment]
> CCRenderer.cpp L866 add `_callbackCommandsPool.push_back(command);` seems fixed the problem.

It dangerous push a callback command to pool 2 times, it will be auto push to pool after execute.
