### ISSUE TITLE
Improve android gradle tool script

### ISSUE THREAD

**Issue by halx99** [axis-project/axis#745]

**Comment by halx99** [comment]
Do you update `app/build.gradle` of your project?

**Comment by halx99** [comment]
OK, try update to latest commit: https://github.com/axis-project/axis/commit/5a1b8074f1a9bc28eaabb955c7eed2e12da11dc4

Then restart android studio to try again

**Comment by Joilnen** [comment]
next commit 5a1b8074f1a9bc28eaabb955c7eed2e12da11dc4


[joilnen@sutherland ~]$ ~/axis_devel/axis20220712/tools/console/bin/axis new -l cpp -d ~
> Copy template into b'/home/joilnen/MyCppGame'
> Rename project name from 'b'HelloCpp'' to 'b'MyCppGame''
> Replace the project name from 'b'HelloCpp'' to 'b'MyCppGame''
> Replace the project package name from 'b'org.cocos2dx.hellocpp'' to 'b'org.cocos2dx.MyCppGame''
> Replace the project SO name from 'b'HelloCpp'' to 'b'MyCppGame''
> Replace the Mac bundle id from 'b'org.cocos2dx.hellocpp'' to 'b'org.cocos2dx.MyCppGame''
> Replace the iOS bundle id from 'b'org.cocos2dx.hellocpp'' to 'b'org.cocos2dx.MyCppGame''
[joilnen@sutherland ~]$ cd MyCppGame/
[joilnen@sutherland MyCppGame]$ ~/axis_devel/axis20220712/tools/console/bin/axis run -p android -j 8 --app-abi armeabi-v7a
Building mode: b'debug'
Using b'Android Studio' project : b'/home/joilnen/MyCppGame/proj.android'
axis version: 1;minor_ver=0
Building apk...
running: 'b'"/home/joilnen/MyCppGame/proj.android/gradlew" --parallel --info assembleDebug -PPROP_BUILD_TYPE=cmake -PPROP_APP_ABI=armeabi-v7a''

Initialized native services in: /home/joilnen/.gradle/native
Initialized jansi services in: /home/joilnen/.gradle/native
The client will now receive all logging from the daemon (pid: 1796). The daemon log file: /home/joilnen/.gradle/daemon/7.4.2/daemon-1796.out.log
Starting 2nd build in daemon [uptime: 2 mins 44.825 secs, performance: 99%, non-heap usage: 24% of 256 MiB]
Using 4 worker leases.
Now considering [/home/joilnen/MyCppGame/proj.android] as hierarchies to watch
Watching the file system is configured to be enabled if available
File system watching is active
Starting Build
Settings evaluated using settings file '/home/joilnen/MyCppGame/proj.android/settings.gradle'.
Projects loaded. Root project using build file '/home/joilnen/MyCppGame/proj.android/build.gradle'.
Included projects: [root project 'MyCppGame', project ':libcocos2dx', project ':MyCppGame']

> Configure project :
Evaluating root project 'MyCppGame' using build file '/home/joilnen/MyCppGame/proj.android/build.gradle'.

> Configure project :libcocos2dx
Evaluating project ':libcocos2dx' using build file '/home/joilnen/.gradle/daemon/7.4.2/null/core/platform/android/libcocos2dx/build.gradle'.

> Configure project :MyCppGame
Evaluating project ':MyCppGame' using build file '/home/joilnen/MyCppGame/proj.android/app/build.gradle'.
Compiling build file '/home/joilnen/MyCppGame/proj.android/app/build.gradle' using SubsetScriptTransformer.
Compiling build file '/home/joilnen/MyCppGame/proj.android/app/build.gradle' using BuildScriptTransformer.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/home/joilnen/MyCppGame/proj.android/app/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating project ':MyCppGame'.
> Could not read script '/home/joilnen/.gradle/daemon/7.4.2/null/core/platform/android/libcocos2dx/axistools.gradle' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':MyCppGame'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Error running command, return code: b'1'.
[joilnen@sutherland MyCppGame]$

**Comment by Joilnen** [comment]
Error that I am getting after that commit


[joilnen@sutherland MyCppGame]$ ~/axis_devel/axis20220712/tools/console/bin/axis compile -p android -j 8 --app-abi armeabi-v7a
Building mode: b'debug'
Using b'Android Studio' project : b'/home/joilnen/MyCppGame/proj.android'
axis version: 1;minor_ver=0
Building apk...
running: 'b'"/home/joilnen/MyCppGame/proj.android/gradlew" --parallel --info assembleDebug -PPROP_BUILD_TYPE=cmake -PPROP_APP_ABI=armeabi-v7a''

Initialized native services in: /home/joilnen/.gradle/native
Initialized jansi services in: /home/joilnen/.gradle/native
Removing 0 daemon stop events from registry
Previous Daemon (803) stopped at Tue Jul 12 11:05:17 BRT 2022 stop command received
Previous Daemon (1796) stopped at Tue Jul 12 11:17:15 BRT 2022 stop command received
Previous Daemon (3367) stopped at Tue Jul 12 11:21:14 BRT 2022 stop command received
Starting a Gradle Daemon, 3 stopped Daemons could not be reused, use --status for details
Starting process 'Gradle build daemon'. Working directory: /home/joilnen/.gradle/daemon/7.4.2 Command: /usr/lib/jvm/java-11-openjdk/bin/java --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /home/joilnen/.gradle/wrapper/dists/gradle-7.4.2-bin/27i1u3m3dkhueqps8aeto1bums/gradle-7.4.2/lib/gradle-launcher-7.4.2.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.4.2
Successfully started process 'Gradle build daemon'
An attempt to start the daemon took 3.412 secs.
The client will now receive all logging from the daemon (pid: 3863). The daemon log file: /home/joilnen/.gradle/daemon/7.4.2/daemon-3863.out.log
Starting build in new daemon [memory: 512 MiB]
Using 4 worker leases.
Watching the file system is configured to be enabled if available
Now considering [/home/joilnen/MyCppGame/proj.android] as hierarchies to watch
File system watching is active
Starting Build
Settings evaluated using settings file '/home/joilnen/MyCppGame/proj.android/settings.gradle'.
Projects loaded. Root project using build file '/home/joilnen/MyCppGame/proj.android/build.gradle'.
Included projects: [root project 'MyCppGame', project ':libcocos2dx', project ':MyCppGame']

> Configure project :
Evaluating root project 'MyCppGame' using build file '/home/joilnen/MyCppGame/proj.android/build.gradle'.

> Configure project :libcocos2dx
Evaluating project ':libcocos2dx' using build file '/home/joilnen/.gradle/daemon/7.4.2/null/core/platform/android/libcocos2dx/build.gradle'.

> Configure project :MyCppGame
Evaluating project ':MyCppGame' using build file '/home/joilnen/MyCppGame/proj.android/app/build.gradle'.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/home/joilnen/MyCppGame/proj.android/app/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating project ':MyCppGame'.
> Could not read script '/home/joilnen/.gradle/daemon/7.4.2/null/core/platform/android/libcocos2dx/axistools.gradle' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':MyCppGame'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Error running command, return code: b'1'.
[joilnen@sutherland MyCppGame]

**Comment by halx99** [comment]
The path `/home/joilnen/.gradle/daemon/7.4.2/null/core/platform/android/libcocos2dx/axistools.gradle` incorrect, I don't know why, I have test on my local machine, it's works

**Comment by Joilnen** [comment]
Ok I got it, it was my .bashrc outdated I didn't do setup.py, thank you, it seems working fine now !
