### ISSUE TITLE
Changing getSpriteFrameByName() with findFrame() in extensions/cocos-studio

### ISSUE THREAD

**Issue by askamn** [axis-project/axis#768]
First, great work on the project!

In extensions/cocos-studio, we have a lot of getSpriteFrameByName() calls. This function has a branch that checks if the frame exists, if not it prints a log. However, at almost all places inside the cocos-studio folder, just after this call we are checking again if the spriteFrame exists. E.g.

```
SpriteFrame* spriteFrame = SpriteFrameCache::getInstance()->getSpriteFrameByName(backGroundTexturePath);
if (spriteFrame)
{
      backGroundFileExist = true;
}
```

So I suggest we replace all calls like this with findFrame() instead which removes the unnecessary branch (as well as the log :P) 
I have already done it in my fork, if you think this should be done, I will open a PR!

Thanks!

**Comment by halx99** [comment]
> 

Good

**Comment by halx99** [comment]
Please send PR
