### ISSUE TITLE
[Feature request] Support for Apple Silicon and Android on X86-64

### ISSUE THREAD

**Issue by pietpukkel** [axis-project/axis#770]
Great work done on this port!   I am looking to port my app to this framework as I see a lot of nice improvements and it seems more future proof.

Would it be possible to out of the box provide the fat libraries (for those without sourcecode) to support Apple Silicon? I've replaced them manually and HelloWorld now compiles and runs perfectly native on my M1 Mac (no idea how GIT works, so can't do a pull request or what ever it is called but happy to provide you with what I have). A small change to the CMake file for PNG is also needed (to include the ARM files for Mac too).

Same goes for Android on X86-64. Some newer chromebooks use x64 intel chips and I need to support those too.

One final thingy; Perhaps you can reconsider renaming the project to axis2d, or axys or axys2d. The issue with just axis is that it is practically unfindable via Google. Everyone and their mother names their projects Axis.  The more people know about this fork the better it is.

**Comment by halx99** [comment]
Sounds Interesting

**Comment by halx99** [comment]
You can refer to https://github.com/axis-project/axis/discussions/411

**Comment by pietpukkel** [comment]
Okay; I'll give it a try.

**Comment by pietpukkel** [comment]
Did something.. no idea if it worked.

**Comment by halx99** [comment]
`axys` looks good to me

**Comment by pietpukkel** [comment]
I've done some more googling and Axys is also quite often used unfortunately.  So for easy finding and referencing it would be better to extend that a bit. Axys2d or AxysXE or something.  I've however gotten used to Axis too ;-)
